version: 2

machine:
  environment:
    SHORT_GIT_HASH: $(echo $CIRCLE_SHA1 | cut -c -7)
    GITREV: ${CIRCLE_SHA1:0:6}

jobs:
  build_api_image:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t andycunn/musigraph-api:$SHORT_GIT_HASH ./Api/src/Api
            docker push andycunn/musigraph-api:$SHORT_GIT_HASH
  deploy_api:
    docker:
      - image: andycunn/helm-deploy:latest
    steps:
      - checkout
      - run:
          name: deploy helm release
          command: |
            helm tiller run -- helm upgrade musigraph-prod --install ./chart --namespace musigraph \
              --set application.version=$SHORT_GIT_HASH \
              --set application.environment=production

workflows:
  version: 2
  deploy:
    jobs:
      - build_api_image:
          context: dotnet
          filters:
            branches:
              only: master
      - deploy_api:
          context: dotnet
          filters:
            branches:
              only: master
          requires:
            - build_api_image