version: 2.1

orbs:
  docker: circleci/docker@0.5.13

jobs:
  deploy_api:
    working_directory: ~/repo
    docker:
      - image: andycunn/local-tiller-deployments:latest
        environment:
          DIGITALOCEAN_ACCESS_TOKEN: $DIGITALOCEAN_ACCESS_TOKEN
    steps:
      - checkout
      - run:
          name: configure kubectl using doctl
          command: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
      - run:
          name: deploy helm release
          command: |
            helm tiller run -- helm upgrade musigraph-prod --install ./Api/infrastructure/chart \
              --namespace musigraph \
              --set application.version=$CIRCLE_SHA1 \
              --set application.environment=production \
              --set discogs.apiToken=$DISCOGS__APITOKEN \
              --set spotify.clientId=$SPOTIFY__CLIENTID \
              --set spotify.clientSecret=$SPOTIFY__CLIENTSECRET

workflows:
  version: 2
  deploy:
    jobs:
      - docker/publish:
          context: dockerhub
          path: ./Api/src/Api
          image: andycunn/musigraph-api
          filters:
            branches:
              only: master
      - deploy_api:
          context: kubernetes
          requires:
            - docker/publish
          filters:
            branches:
              only: master