version: 2

jobs:
  build_api_image:
    docker:
      - image: docker:18.06.1-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t andycunn/musigraph-api:$CIRCLE_SHA1 ./Api/src/Api
            docker push andycunn/musigraph-api:$CIRCLE_SHA1
  deploy_api:
    docker:
      - image: andycunn/helm-deploy:latest
    steps:
      - checkout
      - run:
          name: configure kubectl with gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > /tmp/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
            gcloud --quiet config set project andy-sandbox
            gcloud --quiet config set compute/zone us-west1-a
            gcloud --quiet container clusters get-credentials dev
      - run:
          name: deploy helm release
          command: |
            helm tiller run -- helm upgrade musigraph-prod --install ./Api/infrastructure/chart \
              --namespace musigraph \
              --set application.version=$CIRCLE_SHA1 \
              --set application.environment=production \
              --set discogs.apiToken=$DISCOGS__APITOKEN

workflows:
  version: 2
  deploy:
    jobs:
      - build_api_image:
          context: dotnet
          filters:
            branches:
              only: master
      - deploy_api:
          context: kubernetes
          filters:
            branches:
              only: master
          requires:
            - build_api_image