apiVersion: v1
kind: Service
metadata:
  name: {{ template "postgresql.hasura.fullname" . }}
  labels:
    app: {{ template "postgresql.hasura.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: {{ template "postgresql.hasura.name" . }}
  type: LoadBalancer
