apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "api.fullname" . }}
  labels:
{{ include "api.standardLabels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.application.version }}"
          args:
            - Api.dll
          envFrom:
          - secretRef:
              name: {{ template "api.fullname" . }}-secrets
          - configMapRef:
              name: {{ template "api.fullname" . }}-config
          env:
          - name: APPLICATION__HOST
            valueFrom:
              fieldRef:
                # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
                fieldPath: spec.nodeName
          ports:
            - name: frontend-http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping
              port: frontend-http
          readinessProbe:
            httpGet:
              path: /health
              port: frontend-http
