apiVersion: v1
kind: Service
metadata:
  name: {{ template "api.fullname" . }}
  labels:
{{ include "api.standardLabels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: frontend-http
  selector:
    app: {{ template "api.name" . }}
    release: {{ .Release.Name }}