# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

application:
  environment: Development
  version: latest

ingress:
  domain: api.musigraph.app

image:
  repository: andycunn/musigraph-api
  pullPolicy: Always

cookieDomain: *.musigraph.app

discogs:
  apiToken: ''

spotify:
  clientId: ''
  clientSecret: ''